CREATE DATABASE T_Rental;
GO

USE T_Rental;
GO

-----------DDL-----------

CREATE TABLE EMPRESA (
 idEmpresa TINYINT PRIMARY KEY  IDENTITY(1,1),
 nomeEmpresa VARCHAR(20) NOT NULL
);
GO 

CREATE TABLE CLIENTE (
 idCliente SMALLINT PRIMARY KEY  IDENTITY(1,1),
 nomeCliente VARCHAR(20) NOT NULL,
 sobrenomeCliente VARCHAR (30) NOT NULL,
 cpfCliente CHAR(11) NOT NULL UNIQUE
);
GO 

CREATE TABLE MARCA(
 idMarca SMALLINT PRIMARY KEY  IDENTITY(1,1),
 nomeMarca VARCHAR(20) NOT NULL,
);
GO 

CREATE TABLE MODELO(
idModelo SMALLINT PRIMARY KEY  IDENTITY(1,1),
idMarca SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
nomeModelo VARCHAR(20) NOT NULL
);
GO

CREATE TABLE VEICULO(
idVeiculo SMALLINT PRIMARY KEY  IDENTITY(1,1),
idEmpresa TINYINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
PlacaVeiculo CHAR(7) NOT NULL UNIQUE
);
GO

CREATE TABLE ALUGUEL(
idAluguel SMALLINT PRIMARY KEY  IDENTITY(1,1),
idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idCliente),
Descricao VARCHAR(20) NOT NULL 
);
GO


